export const path = {
  home: "/",
  profile: "/profile",
  information: "/profile/information",
  login: "/login",
  loginAdmin: "/admin/login",
  register: "/register",
  logout: "/logout",
  cart: "/cart",
  productDetail: "/products/:id",
  productClient: "/products",
  adminDashboard: "/admin/dashboard",
  adminProduct: "/admin/products",
  adminProductAdd: "/admin/products/add",
  error401: "/401",
  error404: "/404",
};
